[06/02 13:43:22] 1.8.3
[06/02 13:43:22] MUSH restarted, PID 21676, at Tue Jun 02 13:43:22 2009
[06/02 13:43:22] Unable to open data/indb.gz with libz: No such file or directory

[06/02 13:43:22] Couldn't open data/indb! Creating minimal world.
[06/02 13:43:22] Access file access.cnf not found.
[06/02 13:43:22] Reading /home/e/kilrathi/game/mush.cnf
[06/02 13:43:22] ERROR: Cannot open configuration file alias.cnf.
[06/02 13:43:22] ERROR: Cannot open configuration file restrict.cnf.
[06/02 13:43:22] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/02 13:43:22] Seeding OpenSSL random number pool.
[06/02 13:43:22] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/02 13:43:22] Spawning info slave, communicating using socketpair, pid 21677
[06/02 13:43:22] Unable to open reboot.db in mode 'r': No such file or directory
Listening on port 8888 using IPv4.
[06/02 13:43:22] 1018 file descriptors available.
[06/02 13:43:22] RESTART FINISHED.
[06/02 14:22:08] Terminating info_slave pid 21677
[06/02 14:22:09] Setting ctype locale to en_US.UTF-8
[06/02 14:22:09] Setting time locale to en_US.UTF-8
[06/02 14:22:09] Setting messages locale to en_US.UTF-8
[06/02 14:22:09] Setting collate locale to en_US.UTF-8
[06/02 14:22:09] Seeded RNG from /dev/urandom
[06/02 14:22:09] Reading /home/e/kilrathi/game/mush.cnf
[06/02 14:22:09] Reading alias.cnf
[06/02 14:22:09] Reading restrict.cnf
[06/02 14:22:09] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/02 14:22:09] 1.8.3
[06/02 14:22:09] MUSH restarted, PID 21676, at Tue Jun 02 14:22:09 2009
[06/02 14:22:09] ANALYZING: data/outdb
[06/02 14:22:09] ANALYZING: data/outdb (done)
[06/02 14:22:09] LOADING: data/outdb
[06/02 14:22:09] Loading database saved on Tue Jun 02 21:22:08 2009 UTC
[06/02 14:22:09] READING: done
[06/02 14:22:09] LOADING: data/outdb (done)
[06/02 14:22:09] LOADING: data/maildb
[06/02 14:22:09] LOADING: data/maildb (done)
[06/02 14:22:09] LOADING: data/chatdb
[06/02 14:22:09] LOADING: data/chatdb (done)
[06/02 14:22:09] Access file access.cnf not found.
[06/02 14:22:09] Reading /home/e/kilrathi/game/mush.cnf
[06/02 14:22:09] Reading alias.cnf
[06/02 14:22:09] Reading restrict.cnf
[06/02 14:22:09] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/02 14:22:09] Seeding OpenSSL random number pool.
[06/02 14:22:09] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/02 14:22:09] Spawning info slave, communicating using socketpair, pid 21868
[06/02 14:22:09] 1018 file descriptors available.
[06/02 14:22:09] RESTART FINISHED.
[06/02 14:30:22] Terminating info_slave pid 21868
[06/02 14:30:22] Setting ctype locale to en_US.UTF-8
[06/02 14:30:22] Setting time locale to en_US.UTF-8
[06/02 14:30:22] Setting messages locale to en_US.UTF-8
[06/02 14:30:22] Setting collate locale to en_US.UTF-8
[06/02 14:30:22] Seeded RNG from /dev/urandom
[06/02 14:30:22] Reading /home/e/kilrathi/game/mush.cnf
[06/02 14:30:22] Reading alias.cnf
[06/02 14:30:22] Reading restrict.cnf
[06/02 14:30:22] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/02 14:30:22] 1.8.3
[06/02 14:30:22] MUSH restarted, PID 21676, at Tue Jun 02 14:30:22 2009
[06/02 14:30:22] ANALYZING: data/outdb
[06/02 14:30:22] ANALYZING: data/outdb (done)
[06/02 14:30:22] LOADING: data/outdb
[06/02 14:30:22] Loading database saved on Tue Jun 02 21:30:22 2009 UTC
[06/02 14:30:22] READING: done
[06/02 14:30:22] LOADING: data/outdb (done)
[06/02 14:30:22] LOADING: data/maildb
[06/02 14:30:22] LOADING: data/maildb (done)
[06/02 14:30:22] LOADING: data/chatdb
[06/02 14:30:22] LOADING: data/chatdb (done)
[06/02 14:30:22] Access file access.cnf not found.
[06/02 14:30:22] Reading /home/e/kilrathi/game/mush.cnf
[06/02 14:30:22] Reading alias.cnf
[06/02 14:30:22] Reading restrict.cnf
[06/02 14:30:22] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/02 14:30:22] Seeding OpenSSL random number pool.
[06/02 14:30:22] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/02 14:30:22] Spawning info slave, communicating using socketpair, pid 21925
[06/02 14:30:22] 1018 file descriptors available.
[06/02 14:30:22] RESTART FINISHED.
[06/03 00:11:26] Terminating info_slave pid 21925
[06/03 00:11:27] Setting ctype locale to en_US.UTF-8
[06/03 00:11:27] Setting time locale to en_US.UTF-8
[06/03 00:11:27] Setting messages locale to en_US.UTF-8
[06/03 00:11:27] Setting collate locale to en_US.UTF-8
[06/03 00:11:27] Seeded RNG from /dev/urandom
[06/03 00:11:27] Reading /home/e/kilrathi/game/mush.cnf
[06/03 00:11:27] Reading alias.cnf
[06/03 00:11:27] Reading restrict.cnf
[06/03 00:11:27] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 00:11:27] 1.8.3
[06/03 00:11:27] MUSH restarted, PID 21676, at Wed Jun 03 00:11:27 2009
[06/03 00:11:27] ANALYZING: data/outdb
[06/03 00:11:27] ANALYZING: data/outdb (done)
[06/03 00:11:27] LOADING: data/outdb
[06/03 00:11:27] Loading database saved on Wed Jun 03 07:11:26 2009 UTC
[06/03 00:11:27] READING: done
[06/03 00:11:27] LOADING: data/outdb (done)
[06/03 00:11:27] LOADING: data/maildb
[06/03 00:11:27] LOADING: data/maildb (done)
[06/03 00:11:27] LOADING: data/chatdb
[06/03 00:11:27] LOADING: data/chatdb (done)
[06/03 00:11:27] Access file access.cnf not found.
[06/03 00:11:27] Reading /home/e/kilrathi/game/mush.cnf
[06/03 00:11:27] Reading alias.cnf
[06/03 00:11:27] Reading restrict.cnf
[06/03 00:11:27] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 00:11:27] Initializing PennPy
PennPy: 11
o noes
o noes 2
o noes 3
PennPy: pennmush.example[ example(arg): Equivalent to len(arg) ]
[06/03 00:11:27] Seeding OpenSSL random number pool.
[06/03 00:11:27] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 00:11:27] Spawning info slave, communicating using socketpair, pid 1273
[06/03 00:11:27] 1018 file descriptors available.
[06/03 00:11:27] RESTART FINISHED.
[06/03 00:20:00] Terminating info_slave pid 1273
[06/03 00:20:00] Finalizing PennPy
[06/03 00:20:00] Setting ctype locale to en_US.UTF-8
[06/03 00:20:00] Setting time locale to en_US.UTF-8
[06/03 00:20:00] Setting messages locale to en_US.UTF-8
[06/03 00:20:00] Setting collate locale to en_US.UTF-8
[06/03 00:20:00] Seeded RNG from /dev/urandom
[06/03 00:20:00] Reading /home/e/kilrathi/game/mush.cnf
[06/03 00:20:00] Reading alias.cnf
[06/03 00:20:00] Reading restrict.cnf
[06/03 00:20:00] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 00:20:00] 1.8.3
[06/03 00:20:00] MUSH restarted, PID 21676, at Wed Jun 03 00:20:00 2009
[06/03 00:20:00] ANALYZING: data/outdb
[06/03 00:20:00] ANALYZING: data/outdb (done)
[06/03 00:20:00] LOADING: data/outdb
[06/03 00:20:00] Loading database saved on Wed Jun 03 07:20:00 2009 UTC
[06/03 00:20:00] READING: done
[06/03 00:20:00] LOADING: data/outdb (done)
[06/03 00:20:00] LOADING: data/maildb
[06/03 00:20:00] LOADING: data/maildb (done)
[06/03 00:20:00] LOADING: data/chatdb
[06/03 00:20:00] LOADING: data/chatdb (done)
[06/03 00:20:00] Access file access.cnf not found.
[06/03 00:20:00] Reading /home/e/kilrathi/game/mush.cnf
[06/03 00:20:00] Reading alias.cnf
[06/03 00:20:00] Reading restrict.cnf
[06/03 00:20:00] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 00:20:00] Initializing PennPy
PennPy: 11
o noes
o noes 2
o noes 3
PennPy: pennmush.example[ example(arg): Equivalent to len(arg) ]
[06/03 00:20:00] Seeding OpenSSL random number pool.
[06/03 00:20:00] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 00:20:00] Spawning info slave, communicating using socketpair, pid 1350
[06/03 00:20:00] 1018 file descriptors available.
[06/03 00:20:00] RESTART FINISHED.
[06/03 00:21:58] PennPy: Python exception:
TypeError: empty_fun() takes no arguments (1 given)
[06/03 00:22:28] PennPy: Python exception:
TypeError: test_fun() takes exactly 1 argument (0 given)
[06/03 01:14:47] Terminating info_slave pid 1350
[06/03 01:14:47] Finalizing PennPy
[06/03 01:14:47] Setting ctype locale to en_US.UTF-8
[06/03 01:14:47] Setting time locale to en_US.UTF-8
[06/03 01:14:47] Setting messages locale to en_US.UTF-8
[06/03 01:14:47] Setting collate locale to en_US.UTF-8
[06/03 01:14:47] Seeded RNG from /dev/urandom
[06/03 01:14:47] Reading /home/e/kilrathi/game/mush.cnf
[06/03 01:14:47] Reading alias.cnf
[06/03 01:14:47] Reading restrict.cnf
[06/03 01:14:47] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 01:14:47] 1.8.3
[06/03 01:14:47] MUSH restarted, PID 21676, at Wed Jun 03 01:14:47 2009
[06/03 01:14:47] ANALYZING: data/outdb
[06/03 01:14:47] ANALYZING: data/outdb (done)
[06/03 01:14:47] LOADING: data/outdb
[06/03 01:14:47] Loading database saved on Wed Jun 03 08:14:47 2009 UTC
[06/03 01:14:47] READING: done
[06/03 01:14:47] LOADING: data/outdb (done)
[06/03 01:14:47] LOADING: data/maildb
[06/03 01:14:47] LOADING: data/maildb (done)
[06/03 01:14:47] LOADING: data/chatdb
[06/03 01:14:47] LOADING: data/chatdb (done)
[06/03 01:14:47] Access file access.cnf not found.
[06/03 01:14:47] Reading /home/e/kilrathi/game/mush.cnf
[06/03 01:14:47] Reading alias.cnf
[06/03 01:14:47] Reading restrict.cnf
[06/03 01:14:47] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 01:14:47] Initializing PennPy
PennPy: 11
o noes
o noes 2
o noes 3
PennPy: pennmush.example[ example(arg): Equivalent to len(arg) ]
[06/03 01:14:47] Seeding OpenSSL random number pool.
[06/03 01:14:47] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
[06/03 01:14:47] Spawning info slave, communicating using socketpair, pid 1603
[06/03 01:14:47] 1018 file descriptors available.
[06/03 01:14:47] RESTART FINISHED.
info_slave: trying poll event loop... ok. Using poll.
[06/03 11:58:35] Terminating info_slave pid 1603
[06/03 11:58:35] Finalizing PennPy
[06/03 11:58:36] Setting ctype locale to en_US.UTF-8
[06/03 11:58:36] Setting time locale to en_US.UTF-8
[06/03 11:58:36] Setting messages locale to en_US.UTF-8
[06/03 11:58:36] Setting collate locale to en_US.UTF-8
[06/03 11:58:36] Seeded RNG from /dev/urandom
[06/03 11:58:36] Reading /home/e/kilrathi/game/mush.cnf
[06/03 11:58:36] Reading alias.cnf
[06/03 11:58:36] Reading restrict.cnf
[06/03 11:58:36] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 11:58:36] 1.8.3
[06/03 11:58:36] MUSH restarted, PID 21676, at Wed Jun 03 11:58:36 2009
[06/03 11:58:36] ANALYZING: data/outdb
[06/03 11:58:36] ANALYZING: data/outdb (done)
[06/03 11:58:36] LOADING: data/outdb
[06/03 11:58:36] Loading database saved on Wed Jun 03 18:58:35 2009 UTC
[06/03 11:58:36] READING: done
[06/03 11:58:36] LOADING: data/outdb (done)
[06/03 11:58:36] LOADING: data/maildb
[06/03 11:58:36] LOADING: data/maildb (done)
[06/03 11:58:36] LOADING: data/chatdb
[06/03 11:58:36] LOADING: data/chatdb (done)
[06/03 11:58:36] Access file access.cnf not found.
[06/03 11:58:36] Reading /home/e/kilrathi/game/mush.cnf
[06/03 11:58:36] Reading alias.cnf
[06/03 11:58:36] Reading restrict.cnf
[06/03 11:58:36] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 11:58:36] PennPy: Initializing
[06/03 11:58:36] Seeding OpenSSL random number pool.
[06/03 11:58:36] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 11:58:36] Spawning info slave, communicating using socketpair, pid 8885
[06/03 11:58:36] 1018 file descriptors available.
[06/03 11:58:36] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 11:58:37 2009
[06/03 11:58:37] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 12:06:56] Terminating info_slave pid 8885
[06/03 12:06:56] PennPy: Finalizing
[06/03 12:06:56] Setting ctype locale to en_US.UTF-8
[06/03 12:06:56] Setting time locale to en_US.UTF-8
[06/03 12:06:56] Setting messages locale to en_US.UTF-8
[06/03 12:06:56] Setting collate locale to en_US.UTF-8
[06/03 12:06:56] Seeded RNG from /dev/urandom
[06/03 12:06:56] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:06:56] Reading alias.cnf
[06/03 12:06:56] Reading restrict.cnf
[06/03 12:06:56] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 12:06:56] 1.8.3
[06/03 12:06:56] MUSH restarted, PID 21676, at Wed Jun 03 12:06:56 2009
[06/03 12:06:56] ANALYZING: data/outdb
[06/03 12:06:56] ANALYZING: data/outdb (done)
[06/03 12:06:56] LOADING: data/outdb
[06/03 12:06:56] Loading database saved on Wed Jun 03 19:06:56 2009 UTC
[06/03 12:06:56] READING: done
[06/03 12:06:56] LOADING: data/outdb (done)
[06/03 12:06:56] LOADING: data/maildb
[06/03 12:06:56] LOADING: data/maildb (done)
[06/03 12:06:56] LOADING: data/chatdb
[06/03 12:06:56] LOADING: data/chatdb (done)
[06/03 12:06:56] Access file access.cnf not found.
[06/03 12:06:56] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:06:56] Reading alias.cnf
[06/03 12:06:56] Reading restrict.cnf
[06/03 12:06:56] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 12:06:56] PennPy: Initializing
[06/03 12:06:56] Seeding OpenSSL random number pool.
[06/03 12:06:56] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 12:06:56] Spawning info slave, communicating using socketpair, pid 8918
[06/03 12:06:56] 1018 file descriptors available.
[06/03 12:06:56] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 12:06:57 2009
[06/03 12:06:57] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 12:33:57] Terminating info_slave pid 8918
[06/03 12:33:57] PennPy: Finalizing
[06/03 12:33:57] Setting ctype locale to en_US.UTF-8
[06/03 12:33:57] Setting time locale to en_US.UTF-8
[06/03 12:33:57] Setting messages locale to en_US.UTF-8
[06/03 12:33:57] Setting collate locale to en_US.UTF-8
[06/03 12:33:57] Seeded RNG from /dev/urandom
[06/03 12:33:57] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:33:57] Reading alias.cnf
[06/03 12:33:57] Reading restrict.cnf
[06/03 12:33:57] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 12:33:57] 1.8.3
[06/03 12:33:57] MUSH restarted, PID 21676, at Wed Jun 03 12:33:57 2009
[06/03 12:33:57] ANALYZING: data/outdb
[06/03 12:33:57] ANALYZING: data/outdb (done)
[06/03 12:33:57] LOADING: data/outdb
[06/03 12:33:57] Loading database saved on Wed Jun 03 19:33:57 2009 UTC
[06/03 12:33:57] READING: done
[06/03 12:33:57] LOADING: data/outdb (done)
[06/03 12:33:57] LOADING: data/maildb
[06/03 12:33:57] LOADING: data/maildb (done)
[06/03 12:33:57] LOADING: data/chatdb
[06/03 12:33:57] LOADING: data/chatdb (done)
[06/03 12:33:57] Access file access.cnf not found.
[06/03 12:33:57] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:33:57] Reading alias.cnf
[06/03 12:33:57] Reading restrict.cnf
[06/03 12:33:57] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 12:33:58] PennPy: Initializing
[06/03 12:33:58] Seeding OpenSSL random number pool.
[06/03 12:33:58] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 12:33:58] Spawning info slave, communicating using socketpair, pid 9091
[06/03 12:33:58] 1018 file descriptors available.
[06/03 12:33:58] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 12:33:59 2009
[06/03 12:33:59] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 12:36:09] Terminating info_slave pid 9091
[06/03 12:36:09] PennPy: Finalizing
[06/03 12:36:09] Setting ctype locale to en_US.UTF-8
[06/03 12:36:09] Setting time locale to en_US.UTF-8
[06/03 12:36:09] Setting messages locale to en_US.UTF-8
[06/03 12:36:09] Setting collate locale to en_US.UTF-8
[06/03 12:36:09] Seeded RNG from /dev/urandom
[06/03 12:36:09] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:36:09] Reading alias.cnf
[06/03 12:36:09] Reading restrict.cnf
[06/03 12:36:09] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 12:36:09] 1.8.3
[06/03 12:36:09] MUSH restarted, PID 21676, at Wed Jun 03 12:36:09 2009
[06/03 12:36:09] ANALYZING: data/outdb
[06/03 12:36:09] ANALYZING: data/outdb (done)
[06/03 12:36:09] LOADING: data/outdb
[06/03 12:36:09] Loading database saved on Wed Jun 03 19:36:09 2009 UTC
[06/03 12:36:09] READING: done
[06/03 12:36:09] LOADING: data/outdb (done)
[06/03 12:36:09] LOADING: data/maildb
[06/03 12:36:09] LOADING: data/maildb (done)
[06/03 12:36:09] LOADING: data/chatdb
[06/03 12:36:09] LOADING: data/chatdb (done)
[06/03 12:36:09] Access file access.cnf not found.
[06/03 12:36:09] Reading /home/e/kilrathi/game/mush.cnf
[06/03 12:36:09] Reading alias.cnf
[06/03 12:36:09] Reading restrict.cnf
[06/03 12:36:09] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 12:36:09] PennPy: Initializing
[06/03 12:36:09] Seeding OpenSSL random number pool.
[06/03 12:36:09] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 12:36:09] Spawning info slave, communicating using socketpair, pid 9174
[06/03 12:36:09] 1018 file descriptors available.
[06/03 12:36:09] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 12:36:10 2009
[06/03 12:36:10] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 14:35:13] Terminating info_slave pid 9174
[06/03 14:35:13] PennPy: Finalizing
[06/03 14:35:14] Setting ctype locale to en_US.UTF-8
[06/03 14:35:14] Setting time locale to en_US.UTF-8
[06/03 14:35:14] Setting messages locale to en_US.UTF-8
[06/03 14:35:14] Setting collate locale to en_US.UTF-8
[06/03 14:35:14] Seeded RNG from /dev/urandom
[06/03 14:35:14] Reading /home/e/kilrathi/game/mush.cnf
[06/03 14:35:14] Reading alias.cnf
[06/03 14:35:14] Reading restrict.cnf
[06/03 14:35:14] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 14:35:14] 1.8.3
[06/03 14:35:14] MUSH restarted, PID 21676, at Wed Jun 03 14:35:14 2009
[06/03 14:35:14] ANALYZING: data/outdb
[06/03 14:35:14] ANALYZING: data/outdb (done)
[06/03 14:35:14] LOADING: data/outdb
[06/03 14:35:14] Loading database saved on Wed Jun 03 21:35:13 2009 UTC
[06/03 14:35:14] READING: done
[06/03 14:35:14] LOADING: data/outdb (done)
[06/03 14:35:14] LOADING: data/maildb
[06/03 14:35:14] LOADING: data/maildb (done)
[06/03 14:35:14] LOADING: data/chatdb
[06/03 14:35:14] LOADING: data/chatdb (done)
[06/03 14:35:14] Access file access.cnf not found.
[06/03 14:35:14] Reading /home/e/kilrathi/game/mush.cnf
[06/03 14:35:14] Reading alias.cnf
[06/03 14:35:14] Reading restrict.cnf
[06/03 14:35:14] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 14:35:14] PennPy: Initializing
[06/03 14:35:14] Seeding OpenSSL random number pool.
[06/03 14:35:14] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 14:35:14] Spawning info slave, communicating using socketpair, pid 10096
[06/03 14:35:14] 1018 file descriptors available.
[06/03 14:35:14] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 14:35:15 2009
[06/03 14:35:15] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 19:58:23] Terminating info_slave pid 10096
[06/03 19:58:23] PennPy: Finalizing
[06/03 19:58:23] Setting ctype locale to en_US.UTF-8
[06/03 19:58:23] Setting time locale to en_US.UTF-8
[06/03 19:58:23] Setting messages locale to en_US.UTF-8
[06/03 19:58:23] Setting collate locale to en_US.UTF-8
[06/03 19:58:23] Seeded RNG from /dev/urandom
[06/03 19:58:23] Reading /home/e/kilrathi/game/mush.cnf
[06/03 19:58:23] Reading alias.cnf
[06/03 19:58:23] Reading restrict.cnf
[06/03 19:58:23] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 19:58:23] 1.8.3
[06/03 19:58:23] MUSH restarted, PID 21676, at Wed Jun 03 19:58:23 2009
[06/03 19:58:23] ANALYZING: data/outdb
[06/03 19:58:23] ANALYZING: data/outdb (done)
[06/03 19:58:23] LOADING: data/outdb
[06/03 19:58:23] Loading database saved on Thu Jun 04 02:58:23 2009 UTC
[06/03 19:58:23] READING: done
[06/03 19:58:23] LOADING: data/outdb (done)
[06/03 19:58:23] LOADING: data/maildb
[06/03 19:58:23] LOADING: data/maildb (done)
[06/03 19:58:23] LOADING: data/chatdb
[06/03 19:58:23] LOADING: data/chatdb (done)
[06/03 19:58:23] Access file access.cnf not found.
[06/03 19:58:23] Reading /home/e/kilrathi/game/mush.cnf
[06/03 19:58:23] Reading alias.cnf
[06/03 19:58:23] Reading restrict.cnf
[06/03 19:58:23] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 19:58:23] PennPy: Initializing
[06/03 19:58:23] Seeding OpenSSL random number pool.
[06/03 19:58:23] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 19:58:23] Spawning info slave, communicating using socketpair, pid 11187
[06/03 19:58:23] 1018 file descriptors available.
[06/03 19:58:23] RESTART FINISHED.
[06/03 19:58:23] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 10, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id FROM honor_log WHERE victim = " + victim)
  File "/usr/lib/pymodules/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
periodic() says: The current time is Wed Jun  3 19:58:24 2009
[06/03 19:58:24] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 19:59:09] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 11, in view_honor_log
    pennmush.notify(victim, r"[ansi(hr,Honor log for: [name(%#)]");
NameError: global name 'pennmush' is not defined
[06/03 19:59:30] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 11, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id FROM honor_log WHERE victim = " + victim)
NameError: global name 'pennmush' is not defined
[06/03 19:59:33] Terminating info_slave pid 11187
[06/03 19:59:33] PennPy: Finalizing
[06/03 19:59:33] Setting ctype locale to en_US.UTF-8
[06/03 19:59:33] Setting time locale to en_US.UTF-8
[06/03 19:59:33] Setting messages locale to en_US.UTF-8
[06/03 19:59:33] Setting collate locale to en_US.UTF-8
[06/03 19:59:33] Seeded RNG from /dev/urandom
[06/03 19:59:33] Reading /home/e/kilrathi/game/mush.cnf
[06/03 19:59:33] Reading alias.cnf
[06/03 19:59:33] Reading restrict.cnf
[06/03 19:59:33] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 19:59:33] 1.8.3
[06/03 19:59:33] MUSH restarted, PID 21676, at Wed Jun 03 19:59:33 2009
[06/03 19:59:33] ANALYZING: data/outdb
[06/03 19:59:33] ANALYZING: data/outdb (done)
[06/03 19:59:33] LOADING: data/outdb
[06/03 19:59:33] Loading database saved on Thu Jun 04 02:59:33 2009 UTC
[06/03 19:59:33] READING: done
[06/03 19:59:33] LOADING: data/outdb (done)
[06/03 19:59:33] LOADING: data/maildb
[06/03 19:59:33] LOADING: data/maildb (done)
[06/03 19:59:33] LOADING: data/chatdb
[06/03 19:59:33] LOADING: data/chatdb (done)
[06/03 19:59:33] Access file access.cnf not found.
[06/03 19:59:33] Reading /home/e/kilrathi/game/mush.cnf
[06/03 19:59:33] Reading alias.cnf
[06/03 19:59:33] Reading restrict.cnf
[06/03 19:59:33] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 19:59:33] PennPy: Initializing
[06/03 19:59:33] Seeding OpenSSL random number pool.
[06/03 19:59:33] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 19:59:33] Spawning info slave, communicating using socketpair, pid 11194
[06/03 19:59:33] 1018 file descriptors available.
[06/03 19:59:33] RESTART FINISHED.
[06/03 19:59:33] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    pennmush.notify(victim, r"[ansi(hr,Honor log for: [name(%#)]");
TypeError: an integer is required
periodic() says: The current time is Wed Jun  3 19:59:34 2009
[06/03 19:59:34] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:01:21] Terminating info_slave pid 11194
[06/03 20:01:21] PennPy: Finalizing
[06/03 20:01:22] Setting ctype locale to en_US.UTF-8
[06/03 20:01:22] Setting time locale to en_US.UTF-8
[06/03 20:01:22] Setting messages locale to en_US.UTF-8
[06/03 20:01:22] Setting collate locale to en_US.UTF-8
[06/03 20:01:22] Seeded RNG from /dev/urandom
[06/03 20:01:22] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:01:22] Reading alias.cnf
[06/03 20:01:22] Reading restrict.cnf
[06/03 20:01:22] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:01:22] 1.8.3
[06/03 20:01:22] MUSH restarted, PID 21676, at Wed Jun 03 20:01:22 2009
[06/03 20:01:22] ANALYZING: data/outdb
[06/03 20:01:22] ANALYZING: data/outdb (done)
[06/03 20:01:22] LOADING: data/outdb
[06/03 20:01:22] Loading database saved on Thu Jun 04 03:01:21 2009 UTC
[06/03 20:01:22] READING: done
[06/03 20:01:22] LOADING: data/outdb (done)
[06/03 20:01:22] LOADING: data/maildb
[06/03 20:01:22] LOADING: data/maildb (done)
[06/03 20:01:22] LOADING: data/chatdb
[06/03 20:01:22] LOADING: data/chatdb (done)
[06/03 20:01:22] Access file access.cnf not found.
[06/03 20:01:22] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:01:22] Reading alias.cnf
[06/03 20:01:22] Reading restrict.cnf
[06/03 20:01:22] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:01:22] PennPy: Initializing
Traceback (most recent call last):
  File "python/main.py", line 60, in <module>
    import honor
  File "python/honor.py", line 19
    
    ^
SyntaxError: invalid syntax
[06/03 20:01:22] PennPy: Failed to execute python/main.py
[06/03 20:01:22] Seeding OpenSSL random number pool.
[06/03 20:01:22] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:01:22] Spawning info slave, communicating using socketpair, pid 11202
[06/03 20:01:22] 1018 file descriptors available.
[06/03 20:01:22] RESTART FINISHED.
[06/03 20:02:27] Terminating info_slave pid 11202
[06/03 20:02:27] PennPy: Finalizing
[06/03 20:02:27] Setting ctype locale to en_US.UTF-8
[06/03 20:02:27] Setting time locale to en_US.UTF-8
[06/03 20:02:27] Setting messages locale to en_US.UTF-8
[06/03 20:02:27] Setting collate locale to en_US.UTF-8
[06/03 20:02:27] Seeded RNG from /dev/urandom
[06/03 20:02:27] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:02:27] Reading alias.cnf
[06/03 20:02:27] Reading restrict.cnf
[06/03 20:02:27] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:02:27] 1.8.3
[06/03 20:02:27] MUSH restarted, PID 21676, at Wed Jun 03 20:02:27 2009
[06/03 20:02:27] ANALYZING: data/outdb
[06/03 20:02:27] ANALYZING: data/outdb (done)
[06/03 20:02:27] LOADING: data/outdb
[06/03 20:02:27] Loading database saved on Thu Jun 04 03:02:27 2009 UTC
[06/03 20:02:27] READING: done
[06/03 20:02:27] LOADING: data/outdb (done)
[06/03 20:02:27] LOADING: data/maildb
[06/03 20:02:27] LOADING: data/maildb (done)
[06/03 20:02:27] LOADING: data/chatdb
[06/03 20:02:27] LOADING: data/chatdb (done)
[06/03 20:02:27] Access file access.cnf not found.
[06/03 20:02:27] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:02:27] Reading alias.cnf
[06/03 20:02:27] Reading restrict.cnf
[06/03 20:02:27] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:02:27] PennPy: Initializing
Traceback (most recent call last):
  File "python/main.py", line 60, in <module>
    import honor
  File "python/honor.py", line 19
    
    ^
SyntaxError: invalid syntax
[06/03 20:02:27] PennPy: Failed to execute python/main.py
[06/03 20:02:27] Seeding OpenSSL random number pool.
[06/03 20:02:27] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:02:27] Spawning info slave, communicating using socketpair, pid 11208
[06/03 20:02:27] 1018 file descriptors available.
[06/03 20:02:27] RESTART FINISHED.
[06/03 20:03:13] Terminating info_slave pid 11208
[06/03 20:03:13] PennPy: Finalizing
[06/03 20:03:13] Setting ctype locale to en_US.UTF-8
[06/03 20:03:13] Setting time locale to en_US.UTF-8
[06/03 20:03:13] Setting messages locale to en_US.UTF-8
[06/03 20:03:13] Setting collate locale to en_US.UTF-8
[06/03 20:03:13] Seeded RNG from /dev/urandom
[06/03 20:03:13] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:03:13] Reading alias.cnf
[06/03 20:03:13] Reading restrict.cnf
[06/03 20:03:13] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:03:13] 1.8.3
[06/03 20:03:13] MUSH restarted, PID 21676, at Wed Jun 03 20:03:13 2009
[06/03 20:03:13] ANALYZING: data/outdb
[06/03 20:03:13] ANALYZING: data/outdb (done)
[06/03 20:03:13] LOADING: data/outdb
[06/03 20:03:13] Loading database saved on Thu Jun 04 03:03:13 2009 UTC
[06/03 20:03:13] READING: done
[06/03 20:03:13] LOADING: data/outdb (done)
[06/03 20:03:13] LOADING: data/maildb
[06/03 20:03:13] LOADING: data/maildb (done)
[06/03 20:03:13] LOADING: data/chatdb
[06/03 20:03:13] LOADING: data/chatdb (done)
[06/03 20:03:13] Access file access.cnf not found.
[06/03 20:03:13] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:03:13] Reading alias.cnf
[06/03 20:03:13] Reading restrict.cnf
[06/03 20:03:13] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:03:13] PennPy: Initializing
Traceback (most recent call last):
  File "python/main.py", line 60, in <module>
    import honor
  File "python/honor.py", line 18
    
    ^
SyntaxError: invalid syntax
[06/03 20:03:13] PennPy: Failed to execute python/main.py
[06/03 20:03:13] Seeding OpenSSL random number pool.
[06/03 20:03:13] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:03:13] Spawning info slave, communicating using socketpair, pid 11246
[06/03 20:03:13] 1018 file descriptors available.
[06/03 20:03:13] RESTART FINISHED.
[06/03 20:04:53] Terminating info_slave pid 11246
[06/03 20:04:53] PennPy: Finalizing
[06/03 20:04:54] Setting ctype locale to en_US.UTF-8
[06/03 20:04:54] Setting time locale to en_US.UTF-8
[06/03 20:04:54] Setting messages locale to en_US.UTF-8
[06/03 20:04:54] Setting collate locale to en_US.UTF-8
[06/03 20:04:54] Seeded RNG from /dev/urandom
[06/03 20:04:54] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:04:54] Reading alias.cnf
[06/03 20:04:54] Reading restrict.cnf
[06/03 20:04:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:04:54] 1.8.3
[06/03 20:04:54] MUSH restarted, PID 21676, at Wed Jun 03 20:04:54 2009
[06/03 20:04:54] ANALYZING: data/outdb
[06/03 20:04:54] ANALYZING: data/outdb (done)
[06/03 20:04:54] LOADING: data/outdb
[06/03 20:04:54] Loading database saved on Thu Jun 04 03:04:53 2009 UTC
[06/03 20:04:54] READING: done
[06/03 20:04:54] LOADING: data/outdb (done)
[06/03 20:04:54] LOADING: data/maildb
[06/03 20:04:54] LOADING: data/maildb (done)
[06/03 20:04:54] LOADING: data/chatdb
[06/03 20:04:54] LOADING: data/chatdb (done)
[06/03 20:04:54] Access file access.cnf not found.
[06/03 20:04:54] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:04:54] Reading alias.cnf
[06/03 20:04:54] Reading restrict.cnf
[06/03 20:04:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:04:54] PennPy: Initializing
[06/03 20:04:54] Seeding OpenSSL random number pool.
[06/03 20:04:54] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:04:54] Spawning info slave, communicating using socketpair, pid 11264
[06/03 20:04:54] 1018 file descriptors available.
[06/03 20:04:54] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 20:04:55 2009
[06/03 20:04:55] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:05:19] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    pennmush.notify(victim, r"[ansi(hr,Honor log for: [name(%#)]");
TypeError: an integer is required
[06/03 20:05:55] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id FROM honor_log WHERE victim = " + victim)
TypeError: an integer is required
[06/03 20:05:58] Terminating info_slave pid 11264
[06/03 20:05:58] PennPy: Finalizing
[06/03 20:05:58] Setting ctype locale to en_US.UTF-8
[06/03 20:05:58] Setting time locale to en_US.UTF-8
[06/03 20:05:58] Setting messages locale to en_US.UTF-8
[06/03 20:05:58] Setting collate locale to en_US.UTF-8
[06/03 20:05:58] Seeded RNG from /dev/urandom
[06/03 20:05:58] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:05:58] Reading alias.cnf
[06/03 20:05:58] Reading restrict.cnf
[06/03 20:05:58] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:05:58] 1.8.3
[06/03 20:05:58] MUSH restarted, PID 21676, at Wed Jun 03 20:05:58 2009
[06/03 20:05:58] ANALYZING: data/outdb
[06/03 20:05:58] ANALYZING: data/outdb (done)
[06/03 20:05:58] LOADING: data/outdb
[06/03 20:05:58] Loading database saved on Thu Jun 04 03:05:58 2009 UTC
[06/03 20:05:58] READING: done
[06/03 20:05:58] LOADING: data/outdb (done)
[06/03 20:05:58] LOADING: data/maildb
[06/03 20:05:58] LOADING: data/maildb (done)
[06/03 20:05:58] LOADING: data/chatdb
[06/03 20:05:58] LOADING: data/chatdb (done)
[06/03 20:05:58] Access file access.cnf not found.
[06/03 20:05:58] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:05:58] Reading alias.cnf
[06/03 20:05:58] Reading restrict.cnf
[06/03 20:05:58] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:05:58] PennPy: Initializing
[06/03 20:05:58] Seeding OpenSSL random number pool.
[06/03 20:05:58] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:05:58] Spawning info slave, communicating using socketpair, pid 11267
[06/03 20:05:58] 1018 file descriptors available.
[06/03 20:05:58] RESTART FINISHED.
[06/03 20:05:58] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id FROM honor_log WHERE victim = " + victim)
TypeError: cannot concatenate 'str' and 'int' objects
periodic() says: The current time is Wed Jun  3 20:05:59 2009
[06/03 20:05:59] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:06:02] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id FROM honor_log WHERE victim = " + victim)
TypeError: cannot concatenate 'str' and 'int' objects
[06/03 20:06:40] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 12, in view_honor_log
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id
TypeError: cannot concatenate 'str' and 'int' objects
[06/03 20:06:45] Terminating info_slave pid 11267
[06/03 20:06:45] PennPy: Finalizing
[06/03 20:06:46] Setting ctype locale to en_US.UTF-8
[06/03 20:06:46] Setting time locale to en_US.UTF-8
[06/03 20:06:46] Setting messages locale to en_US.UTF-8
[06/03 20:06:46] Setting collate locale to en_US.UTF-8
[06/03 20:06:46] Seeded RNG from /dev/urandom
[06/03 20:06:46] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:06:46] Reading alias.cnf
[06/03 20:06:46] Reading restrict.cnf
[06/03 20:06:46] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:06:46] 1.8.3
[06/03 20:06:46] MUSH restarted, PID 21676, at Wed Jun 03 20:06:46 2009
[06/03 20:06:46] ANALYZING: data/outdb
[06/03 20:06:46] ANALYZING: data/outdb (done)
[06/03 20:06:46] LOADING: data/outdb
[06/03 20:06:46] Loading database saved on Thu Jun 04 03:06:45 2009 UTC
[06/03 20:06:46] READING: done
[06/03 20:06:46] LOADING: data/outdb (done)
[06/03 20:06:46] LOADING: data/maildb
[06/03 20:06:46] LOADING: data/maildb (done)
[06/03 20:06:46] LOADING: data/chatdb
[06/03 20:06:46] LOADING: data/chatdb (done)
[06/03 20:06:46] Access file access.cnf not found.
[06/03 20:06:46] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:06:46] Reading alias.cnf
[06/03 20:06:46] Reading restrict.cnf
[06/03 20:06:46] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:06:46] PennPy: Initializing
Traceback (most recent call last):
  File "python/main.py", line 60, in <module>
    import honor
  File "python/honor.py", line 12
    cursor.execute("SELECT delta, balance, description, parent_honor_log_id
                                                                          ^
SyntaxError: EOL while scanning single-quoted string
[06/03 20:06:46] PennPy: Failed to execute python/main.py
[06/03 20:06:46] Seeding OpenSSL random number pool.
[06/03 20:06:46] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:06:46] Spawning info slave, communicating using socketpair, pid 11269
[06/03 20:06:46] 1018 file descriptors available.
[06/03 20:06:46] RESTART FINISHED.
[06/03 20:07:24] Terminating info_slave pid 11269
[06/03 20:07:24] PennPy: Finalizing
[06/03 20:07:24] Setting ctype locale to en_US.UTF-8
[06/03 20:07:24] Setting time locale to en_US.UTF-8
[06/03 20:07:24] Setting messages locale to en_US.UTF-8
[06/03 20:07:24] Setting collate locale to en_US.UTF-8
[06/03 20:07:24] Seeded RNG from /dev/urandom
[06/03 20:07:24] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:07:24] Reading alias.cnf
[06/03 20:07:24] Reading restrict.cnf
[06/03 20:07:24] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:07:25] 1.8.3
[06/03 20:07:25] MUSH restarted, PID 21676, at Wed Jun 03 20:07:25 2009
[06/03 20:07:25] ANALYZING: data/outdb
[06/03 20:07:25] ANALYZING: data/outdb (done)
[06/03 20:07:25] LOADING: data/outdb
[06/03 20:07:25] Loading database saved on Thu Jun 04 03:07:24 2009 UTC
[06/03 20:07:25] READING: done
[06/03 20:07:25] LOADING: data/outdb (done)
[06/03 20:07:25] LOADING: data/maildb
[06/03 20:07:25] LOADING: data/maildb (done)
[06/03 20:07:25] LOADING: data/chatdb
[06/03 20:07:25] LOADING: data/chatdb (done)
[06/03 20:07:25] Access file access.cnf not found.
[06/03 20:07:25] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:07:25] Reading alias.cnf
[06/03 20:07:25] Reading restrict.cnf
[06/03 20:07:25] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:07:25] PennPy: Initializing
[06/03 20:07:25] Seeding OpenSSL random number pool.
[06/03 20:07:25] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:07:25] Spawning info slave, communicating using socketpair, pid 11272
[06/03 20:07:25] 1018 file descriptors available.
[06/03 20:07:25] RESTART FINISHED.
[06/03 20:07:25] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 13, in view_honor_log
    pennmush.notify(victim, r"[ansi(hr,Honor log for: [name(%#)]");
TypeError: 'int' object is not iterable
periodic() says: The current time is Wed Jun  3 20:07:26 2009
[06/03 20:07:26] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:08:10] Terminating info_slave pid 11272
[06/03 20:08:10] PennPy: Finalizing
[06/03 20:08:11] Setting ctype locale to en_US.UTF-8
[06/03 20:08:11] Setting time locale to en_US.UTF-8
[06/03 20:08:11] Setting messages locale to en_US.UTF-8
[06/03 20:08:11] Setting collate locale to en_US.UTF-8
[06/03 20:08:11] Seeded RNG from /dev/urandom
[06/03 20:08:11] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:08:11] Reading alias.cnf
[06/03 20:08:11] Reading restrict.cnf
[06/03 20:08:11] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:08:11] 1.8.3
[06/03 20:08:11] MUSH restarted, PID 21676, at Wed Jun 03 20:08:11 2009
[06/03 20:08:11] ANALYZING: data/outdb
[06/03 20:08:11] ANALYZING: data/outdb (done)
[06/03 20:08:11] LOADING: data/outdb
[06/03 20:08:11] Loading database saved on Thu Jun 04 03:08:10 2009 UTC
[06/03 20:08:11] READING: done
[06/03 20:08:11] LOADING: data/outdb (done)
[06/03 20:08:11] LOADING: data/maildb
[06/03 20:08:11] LOADING: data/maildb (done)
[06/03 20:08:11] LOADING: data/chatdb
[06/03 20:08:11] LOADING: data/chatdb (done)
[06/03 20:08:11] Access file access.cnf not found.
[06/03 20:08:11] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:08:11] Reading alias.cnf
[06/03 20:08:11] Reading restrict.cnf
[06/03 20:08:11] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:08:11] PennPy: Initializing
[06/03 20:08:11] Seeding OpenSSL random number pool.
[06/03 20:08:11] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:08:11] Spawning info slave, communicating using socketpair, pid 11274
[06/03 20:08:11] 1018 file descriptors available.
[06/03 20:08:11] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 20:08:12 2009
[06/03 20:08:12] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:08:13] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 14, in view_honor_log
    for (delta, balance) in cursor.fetchall():
ValueError: too many values to unpack
[06/03 20:08:41] Terminating info_slave pid 11274
[06/03 20:08:41] PennPy: Finalizing
[06/03 20:08:41] Setting ctype locale to en_US.UTF-8
[06/03 20:08:41] Setting time locale to en_US.UTF-8
[06/03 20:08:41] Setting messages locale to en_US.UTF-8
[06/03 20:08:41] Setting collate locale to en_US.UTF-8
[06/03 20:08:41] Seeded RNG from /dev/urandom
[06/03 20:08:41] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:08:41] Reading alias.cnf
[06/03 20:08:41] Reading restrict.cnf
[06/03 20:08:41] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:08:41] 1.8.3
[06/03 20:08:41] MUSH restarted, PID 21676, at Wed Jun 03 20:08:41 2009
[06/03 20:08:41] ANALYZING: data/outdb
[06/03 20:08:41] ANALYZING: data/outdb (done)
[06/03 20:08:41] LOADING: data/outdb
[06/03 20:08:41] Loading database saved on Thu Jun 04 03:08:41 2009 UTC
[06/03 20:08:41] READING: done
[06/03 20:08:41] LOADING: data/outdb (done)
[06/03 20:08:41] LOADING: data/maildb
[06/03 20:08:41] LOADING: data/maildb (done)
[06/03 20:08:41] LOADING: data/chatdb
[06/03 20:08:41] LOADING: data/chatdb (done)
[06/03 20:08:41] Access file access.cnf not found.
[06/03 20:08:41] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:08:41] Reading alias.cnf
[06/03 20:08:41] Reading restrict.cnf
[06/03 20:08:41] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:08:41] PennPy: Initializing
[06/03 20:08:41] Seeding OpenSSL random number pool.
[06/03 20:08:41] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:08:41] Spawning info slave, communicating using socketpair, pid 11276
[06/03 20:08:41] 1018 file descriptors available.
[06/03 20:08:41] RESTART FINISHED.
[06/03 20:08:41] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in honor_view
    honor.view_honor_log(victim)
  File "python/honor.py", line 15, in view_honor_log
    pennmush.notify([victim], delta + " " + balance)
TypeError: unsupported operand type(s) for +: 'long' and 'str'
periodic() says: The current time is Wed Jun  3 20:08:42 2009
[06/03 20:08:42] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/03 20:17:45] Terminating info_slave pid 11276
[06/03 20:17:45] PennPy: Finalizing
[06/03 20:17:45] Setting ctype locale to en_US.UTF-8
[06/03 20:17:45] Setting time locale to en_US.UTF-8
[06/03 20:17:45] Setting messages locale to en_US.UTF-8
[06/03 20:17:45] Setting collate locale to en_US.UTF-8
[06/03 20:17:45] Seeded RNG from /dev/urandom
[06/03 20:17:45] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:17:45] Reading alias.cnf
[06/03 20:17:45] Reading restrict.cnf
[06/03 20:17:45] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/03 20:17:45] 1.8.3
[06/03 20:17:45] MUSH restarted, PID 21676, at Wed Jun 03 20:17:45 2009
[06/03 20:17:45] ANALYZING: data/outdb
[06/03 20:17:45] ANALYZING: data/outdb (done)
[06/03 20:17:45] LOADING: data/outdb
[06/03 20:17:45] Loading database saved on Thu Jun 04 03:17:45 2009 UTC
[06/03 20:17:45] READING: done
[06/03 20:17:45] LOADING: data/outdb (done)
[06/03 20:17:45] LOADING: data/maildb
[06/03 20:17:45] LOADING: data/maildb (done)
[06/03 20:17:45] LOADING: data/chatdb
[06/03 20:17:45] LOADING: data/chatdb (done)
[06/03 20:17:45] Access file access.cnf not found.
[06/03 20:17:45] Reading /home/e/kilrathi/game/mush.cnf
[06/03 20:17:45] Reading alias.cnf
[06/03 20:17:45] Reading restrict.cnf
[06/03 20:17:45] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/03 20:17:45] PennPy: Initializing
[06/03 20:17:45] Seeding OpenSSL random number pool.
[06/03 20:17:45] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/03 20:17:45] Spawning info slave, communicating using socketpair, pid 11334
[06/03 20:17:45] 1018 file descriptors available.
[06/03 20:17:45] RESTART FINISHED.
periodic() says: The current time is Wed Jun  3 20:17:46 2009
[06/03 20:17:46] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 09:27:06] Terminating info_slave pid 11334
[06/04 09:27:06] PennPy: Finalizing
[06/04 09:27:06] Setting ctype locale to en_US.UTF-8
[06/04 09:27:06] Setting time locale to en_US.UTF-8
[06/04 09:27:06] Setting messages locale to en_US.UTF-8
[06/04 09:27:06] Setting collate locale to en_US.UTF-8
[06/04 09:27:06] Seeded RNG from /dev/urandom
[06/04 09:27:06] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:27:06] Reading alias.cnf
[06/04 09:27:06] Reading restrict.cnf
[06/04 09:27:06] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 09:27:06] 1.8.3
[06/04 09:27:06] MUSH restarted, PID 21676, at Thu Jun 04 09:27:06 2009
[06/04 09:27:06] ANALYZING: data/outdb
[06/04 09:27:06] ANALYZING: data/outdb (done)
[06/04 09:27:06] LOADING: data/outdb
[06/04 09:27:06] Loading database saved on Thu Jun 04 16:27:06 2009 UTC
[06/04 09:27:06] READING: done
[06/04 09:27:06] LOADING: data/outdb (done)
[06/04 09:27:06] LOADING: data/maildb
[06/04 09:27:06] LOADING: data/maildb (done)
[06/04 09:27:06] LOADING: data/chatdb
[06/04 09:27:06] LOADING: data/chatdb (done)
[06/04 09:27:06] Access file access.cnf not found.
[06/04 09:27:06] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:27:06] Reading alias.cnf
[06/04 09:27:06] Reading restrict.cnf
[06/04 09:27:06] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 09:27:06] PennPy: Initializing
  File "python/main.py", line 65
    conn = 
          ^
SyntaxError: invalid syntax
[06/04 09:27:06] PennPy: Failed to execute python/main.py
[06/04 09:27:06] Seeding OpenSSL random number pool.
[06/04 09:27:06] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 09:27:06] Spawning info slave, communicating using socketpair, pid 14005
[06/04 09:27:06] 1018 file descriptors available.
[06/04 09:27:06] RESTART FINISHED.
[06/04 09:39:12] Terminating info_slave pid 14005
[06/04 09:39:12] PennPy: Finalizing
[06/04 09:39:12] Setting ctype locale to en_US.UTF-8
[06/04 09:39:12] Setting time locale to en_US.UTF-8
[06/04 09:39:12] Setting messages locale to en_US.UTF-8
[06/04 09:39:12] Setting collate locale to en_US.UTF-8
[06/04 09:39:12] Seeded RNG from /dev/urandom
[06/04 09:39:12] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:39:12] Reading alias.cnf
[06/04 09:39:12] Reading restrict.cnf
[06/04 09:39:12] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 09:39:12] 1.8.3
[06/04 09:39:12] MUSH restarted, PID 21676, at Thu Jun 04 09:39:12 2009
[06/04 09:39:12] ANALYZING: data/outdb
[06/04 09:39:12] ANALYZING: data/outdb (done)
[06/04 09:39:12] LOADING: data/outdb
[06/04 09:39:12] Loading database saved on Thu Jun 04 16:39:12 2009 UTC
[06/04 09:39:12] READING: done
[06/04 09:39:12] LOADING: data/outdb (done)
[06/04 09:39:12] LOADING: data/maildb
[06/04 09:39:12] LOADING: data/maildb (done)
[06/04 09:39:12] LOADING: data/chatdb
[06/04 09:39:12] LOADING: data/chatdb (done)
[06/04 09:39:12] Access file access.cnf not found.
[06/04 09:39:12] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:39:12] Reading alias.cnf
[06/04 09:39:12] Reading restrict.cnf
[06/04 09:39:12] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 09:39:13] PennPy: Initializing
  File "python/main.py", line 60
    def reload(module)
                     ^
SyntaxError: invalid syntax
[06/04 09:39:13] PennPy: Failed to execute python/main.py
[06/04 09:39:13] Seeding OpenSSL random number pool.
[06/04 09:39:13] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 09:39:13] Spawning info slave, communicating using socketpair, pid 14148
[06/04 09:39:13] 1018 file descriptors available.
[06/04 09:39:13] RESTART FINISHED.
[06/04 09:40:25] Terminating info_slave pid 14148
[06/04 09:40:25] PennPy: Finalizing
[06/04 09:40:26] Setting ctype locale to en_US.UTF-8
[06/04 09:40:26] Setting time locale to en_US.UTF-8
[06/04 09:40:26] Setting messages locale to en_US.UTF-8
[06/04 09:40:26] Setting collate locale to en_US.UTF-8
[06/04 09:40:26] Seeded RNG from /dev/urandom
[06/04 09:40:26] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:40:26] Reading alias.cnf
[06/04 09:40:26] Reading restrict.cnf
[06/04 09:40:26] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 09:40:26] 1.8.3
[06/04 09:40:26] MUSH restarted, PID 21676, at Thu Jun 04 09:40:26 2009
[06/04 09:40:26] ANALYZING: data/outdb
[06/04 09:40:26] ANALYZING: data/outdb (done)
[06/04 09:40:26] LOADING: data/outdb
[06/04 09:40:26] Loading database saved on Thu Jun 04 16:40:25 2009 UTC
[06/04 09:40:26] READING: done
[06/04 09:40:26] LOADING: data/outdb (done)
[06/04 09:40:26] LOADING: data/maildb
[06/04 09:40:26] LOADING: data/maildb (done)
[06/04 09:40:26] LOADING: data/chatdb
[06/04 09:40:26] LOADING: data/chatdb (done)
[06/04 09:40:26] Access file access.cnf not found.
[06/04 09:40:26] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:40:26] Reading alias.cnf
[06/04 09:40:26] Reading restrict.cnf
[06/04 09:40:26] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 09:40:26] PennPy: Initializing
[06/04 09:40:26] Seeding OpenSSL random number pool.
[06/04 09:40:26] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 09:40:26] Spawning info slave, communicating using socketpair, pid 14189
[06/04 09:40:26] 1018 file descriptors available.
[06/04 09:40:26] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 09:40:27 2009
[06/04 09:40:27] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 09:41:59] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 61, in reload
    reload(sys.modules[module])
NameError: global name 'sys' is not defined
[06/04 09:44:25] Terminating info_slave pid 14189
[06/04 09:44:25] PennPy: Finalizing
[06/04 09:44:26] Setting ctype locale to en_US.UTF-8
[06/04 09:44:26] Setting time locale to en_US.UTF-8
[06/04 09:44:26] Setting messages locale to en_US.UTF-8
[06/04 09:44:26] Setting collate locale to en_US.UTF-8
[06/04 09:44:26] Seeded RNG from /dev/urandom
[06/04 09:44:26] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:44:26] Reading alias.cnf
[06/04 09:44:26] Reading restrict.cnf
[06/04 09:44:26] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 09:44:26] 1.8.3
[06/04 09:44:26] MUSH restarted, PID 21676, at Thu Jun 04 09:44:26 2009
[06/04 09:44:26] ANALYZING: data/outdb
[06/04 09:44:26] ANALYZING: data/outdb (done)
[06/04 09:44:26] LOADING: data/outdb
[06/04 09:44:26] Loading database saved on Thu Jun 04 16:44:25 2009 UTC
[06/04 09:44:26] READING: done
[06/04 09:44:26] LOADING: data/outdb (done)
[06/04 09:44:26] LOADING: data/maildb
[06/04 09:44:26] LOADING: data/maildb (done)
[06/04 09:44:26] LOADING: data/chatdb
[06/04 09:44:26] LOADING: data/chatdb (done)
[06/04 09:44:26] Access file access.cnf not found.
[06/04 09:44:26] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:44:26] Reading alias.cnf
[06/04 09:44:26] Reading restrict.cnf
[06/04 09:44:26] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 09:44:26] PennPy: Initializing
[06/04 09:44:26] Seeding OpenSSL random number pool.
[06/04 09:44:26] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 09:44:26] Spawning info slave, communicating using socketpair, pid 14193
[06/04 09:44:26] 1018 file descriptors available.
[06/04 09:44:26] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 09:44:27 2009
[06/04 09:44:27] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 51, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 09:44:33] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 59, in reload
    reload(sys.modules[module])
  File "python/main.py", line 59, in reload
    reload(sys.modules[module])
KeyError: <module 'honor' from 'python/honor.py'>
[06/04 09:46:06] Terminating info_slave pid 14193
[06/04 09:46:06] PennPy: Finalizing
[06/04 09:46:07] Setting ctype locale to en_US.UTF-8
[06/04 09:46:07] Setting time locale to en_US.UTF-8
[06/04 09:46:07] Setting messages locale to en_US.UTF-8
[06/04 09:46:07] Setting collate locale to en_US.UTF-8
[06/04 09:46:07] Seeded RNG from /dev/urandom
[06/04 09:46:07] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:46:07] Reading alias.cnf
[06/04 09:46:07] Reading restrict.cnf
[06/04 09:46:07] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 09:46:07] 1.8.3
[06/04 09:46:07] MUSH restarted, PID 21676, at Thu Jun 04 09:46:07 2009
[06/04 09:46:07] ANALYZING: data/outdb
[06/04 09:46:07] ANALYZING: data/outdb (done)
[06/04 09:46:07] LOADING: data/outdb
[06/04 09:46:07] Loading database saved on Thu Jun 04 16:46:06 2009 UTC
[06/04 09:46:07] READING: done
[06/04 09:46:07] LOADING: data/outdb (done)
[06/04 09:46:07] LOADING: data/maildb
[06/04 09:46:07] LOADING: data/maildb (done)
[06/04 09:46:07] LOADING: data/chatdb
[06/04 09:46:07] LOADING: data/chatdb (done)
[06/04 09:46:07] Access file access.cnf not found.
[06/04 09:46:07] Reading /home/e/kilrathi/game/mush.cnf
[06/04 09:46:07] Reading alias.cnf
[06/04 09:46:07] Reading restrict.cnf
[06/04 09:46:07] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 09:46:08] PennPy: Initializing
[06/04 09:46:08] Seeding OpenSSL random number pool.
[06/04 09:46:08] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 09:46:08] Spawning info slave, communicating using socketpair, pid 14195
[06/04 09:46:08] 1018 file descriptors available.
[06/04 09:46:08] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 09:46:09 2009
[06/04 09:46:09] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 09:46:37] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in reload
    reload(sys.modules[module])
  File "python/main.py", line 62, in reload
    reload(sys.modules[module])
KeyError: <module 'honor' from 'python/honor.pyc'>
[06/04 10:02:25] Terminating info_slave pid 14195
[06/04 10:02:25] PennPy: Finalizing
[06/04 10:02:25] Setting ctype locale to en_US.UTF-8
[06/04 10:02:25] Setting time locale to en_US.UTF-8
[06/04 10:02:25] Setting messages locale to en_US.UTF-8
[06/04 10:02:25] Setting collate locale to en_US.UTF-8
[06/04 10:02:25] Seeded RNG from /dev/urandom
[06/04 10:02:25] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:02:25] Reading alias.cnf
[06/04 10:02:25] Reading restrict.cnf
[06/04 10:02:25] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 10:02:25] 1.8.3
[06/04 10:02:25] MUSH restarted, PID 21676, at Thu Jun 04 10:02:25 2009
[06/04 10:02:25] ANALYZING: data/outdb
[06/04 10:02:25] ANALYZING: data/outdb (done)
[06/04 10:02:25] LOADING: data/outdb
[06/04 10:02:25] Loading database saved on Thu Jun 04 17:02:25 2009 UTC
[06/04 10:02:25] READING: done
[06/04 10:02:25] LOADING: data/outdb (done)
[06/04 10:02:25] LOADING: data/maildb
[06/04 10:02:25] LOADING: data/maildb (done)
[06/04 10:02:25] LOADING: data/chatdb
[06/04 10:02:25] LOADING: data/chatdb (done)
[06/04 10:02:25] Access file access.cnf not found.
[06/04 10:02:25] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:02:25] Reading alias.cnf
[06/04 10:02:25] Reading restrict.cnf
[06/04 10:02:25] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 10:02:25] PennPy: Initializing
[06/04 10:02:25] Seeding OpenSSL random number pool.
[06/04 10:02:25] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 10:02:25] Spawning info slave, communicating using socketpair, pid 14212
[06/04 10:02:25] 1018 file descriptors available.
[06/04 10:02:25] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 10:02:26 2009
[06/04 10:02:26] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 10:02:28] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 62, in reload
    reload(sys.modules[module])
  File "python/main.py", line 62, in reload
    reload(sys.modules[module])
KeyError: <module 'honor' from 'python/honor.pyc'>
[06/04 10:08:15] Terminating info_slave pid 14212
[06/04 10:08:15] PennPy: Finalizing
[06/04 10:08:15] Setting ctype locale to en_US.UTF-8
[06/04 10:08:15] Setting time locale to en_US.UTF-8
[06/04 10:08:15] Setting messages locale to en_US.UTF-8
[06/04 10:08:15] Setting collate locale to en_US.UTF-8
[06/04 10:08:15] Seeded RNG from /dev/urandom
[06/04 10:08:15] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:08:15] Reading alias.cnf
[06/04 10:08:15] Reading restrict.cnf
[06/04 10:08:15] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 10:08:15] 1.8.3
[06/04 10:08:15] MUSH restarted, PID 21676, at Thu Jun 04 10:08:15 2009
[06/04 10:08:15] ANALYZING: data/outdb
[06/04 10:08:15] ANALYZING: data/outdb (done)
[06/04 10:08:15] LOADING: data/outdb
[06/04 10:08:15] Loading database saved on Thu Jun 04 17:08:15 2009 UTC
[06/04 10:08:15] READING: done
[06/04 10:08:15] LOADING: data/outdb (done)
[06/04 10:08:15] LOADING: data/maildb
[06/04 10:08:15] LOADING: data/maildb (done)
[06/04 10:08:15] LOADING: data/chatdb
[06/04 10:08:15] LOADING: data/chatdb (done)
[06/04 10:08:15] Access file access.cnf not found.
[06/04 10:08:15] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:08:15] Reading alias.cnf
[06/04 10:08:15] Reading restrict.cnf
[06/04 10:08:15] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 10:08:16] PennPy: Initializing
[06/04 10:08:16] Seeding OpenSSL random number pool.
[06/04 10:08:16] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 10:08:16] Spawning info slave, communicating using socketpair, pid 14215
[06/04 10:08:16] 1018 file descriptors available.
[06/04 10:08:16] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 10:08:17 2009
[06/04 10:08:17] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 10:41:28] Terminating info_slave pid 14215
[06/04 10:41:28] PennPy: Finalizing
[06/04 10:41:29] Setting ctype locale to en_US.UTF-8
[06/04 10:41:29] Setting time locale to en_US.UTF-8
[06/04 10:41:29] Setting messages locale to en_US.UTF-8
[06/04 10:41:29] Setting collate locale to en_US.UTF-8
[06/04 10:41:29] Seeded RNG from /dev/urandom
[06/04 10:41:29] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:41:29] Reading alias.cnf
[06/04 10:41:29] Reading restrict.cnf
[06/04 10:41:29] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 10:41:29] 1.8.3
[06/04 10:41:29] MUSH restarted, PID 21676, at Thu Jun 04 10:41:29 2009
[06/04 10:41:29] ANALYZING: data/outdb
[06/04 10:41:29] ANALYZING: data/outdb (done)
[06/04 10:41:29] LOADING: data/outdb
[06/04 10:41:29] Loading database saved on Thu Jun 04 17:41:28 2009 UTC
[06/04 10:41:29] READING: done
[06/04 10:41:29] LOADING: data/outdb (done)
[06/04 10:41:29] LOADING: data/maildb
[06/04 10:41:29] LOADING: data/maildb (done)
[06/04 10:41:29] LOADING: data/chatdb
[06/04 10:41:29] LOADING: data/chatdb (done)
[06/04 10:41:29] Access file access.cnf not found.
[06/04 10:41:29] Reading /home/e/kilrathi/game/mush.cnf
[06/04 10:41:29] Reading alias.cnf
[06/04 10:41:29] Reading restrict.cnf
[06/04 10:41:29] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 10:41:29] PennPy: Initializing
_DB_KEY_NAME = 0
[06/04 10:41:29] Seeding OpenSSL random number pool.
[06/04 10:41:29] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 10:41:29] Spawning info slave, communicating using socketpair, pid 14468
[06/04 10:41:29] 1018 file descriptors available.
[06/04 10:41:29] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 10:41:31 2009
[06/04 10:41:31] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 53, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 10:46:26] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 66, in reload
    __builtins__.reload(sys.modules[module])
KeyError: 'main'
[06/04 10:48:06] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 76, in honor_view
    
  File "/home/e/kilrathi/game/python/honor.py", line 10, in view_honor_log
    if not conn:
UnboundLocalError: local variable 'conn' referenced before assignment
[06/04 10:48:23] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 76, in honor_view
    
  File "python/honor.py", line 14, in view_honor_log
    cursor = db.conn.cursor()
AttributeError: 'module' object has no attribute 'conn'
[06/04 14:50:15] Terminating info_slave pid 14468
[06/04 14:50:15] PennPy: Finalizing
[06/04 14:50:15] Setting ctype locale to en_US.UTF-8
[06/04 14:50:15] Setting time locale to en_US.UTF-8
[06/04 14:50:15] Setting messages locale to en_US.UTF-8
[06/04 14:50:15] Setting collate locale to en_US.UTF-8
[06/04 14:50:15] Seeded RNG from /dev/urandom
[06/04 14:50:15] Reading /home/e/kilrathi/game/mush.cnf
[06/04 14:50:15] Reading alias.cnf
[06/04 14:50:15] Reading restrict.cnf
[06/04 14:50:15] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/04 14:50:15] 1.8.3
[06/04 14:50:15] MUSH restarted, PID 21676, at Thu Jun 04 14:50:15 2009
[06/04 14:50:15] ANALYZING: data/outdb
[06/04 14:50:15] ANALYZING: data/outdb (done)
[06/04 14:50:15] LOADING: data/outdb
[06/04 14:50:15] Loading database saved on Thu Jun 04 21:50:15 2009 UTC
[06/04 14:50:15] READING: done
[06/04 14:50:15] LOADING: data/outdb (done)
[06/04 14:50:15] LOADING: data/maildb
[06/04 14:50:15] LOADING: data/maildb (done)
[06/04 14:50:15] LOADING: data/chatdb
[06/04 14:50:15] LOADING: data/chatdb (done)
[06/04 14:50:15] Access file access.cnf not found.
[06/04 14:50:15] Reading /home/e/kilrathi/game/mush.cnf
[06/04 14:50:15] Reading alias.cnf
[06/04 14:50:15] Reading restrict.cnf
[06/04 14:50:15] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/04 14:50:15] PennPy: Initializing
_DB_KEY_NAME = 0
[06/04 14:50:15] Seeding OpenSSL random number pool.
[06/04 14:50:15] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/04 14:50:15] Spawning info slave, communicating using socketpair, pid 15846
[06/04 14:50:15] 1018 file descriptors available.
[06/04 14:50:15] RESTART FINISHED.
periodic() says: The current time is Thu Jun  4 14:50:16 2009
[06/04 14:50:16] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/04 16:27:29] PennPy: Python exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python/honor.py", line 13, in view_honor_log
    victim = int(victim.lstrip("#"))
AttributeError: 'int' object has no attribute 'lstrip'
[06/09 10:52:18] Terminating info_slave pid 15846
[06/09 10:52:18] PennPy: Finalizing
[06/09 10:52:19] Setting ctype locale to en_US.UTF-8
[06/09 10:52:19] Setting time locale to en_US.UTF-8
[06/09 10:52:19] Setting messages locale to en_US.UTF-8
[06/09 10:52:19] Setting collate locale to en_US.UTF-8
[06/09 10:52:19] Seeded RNG from /dev/urandom
[06/09 10:52:19] Reading /home/e/kilrathi/game/mush.cnf
[06/09 10:52:19] Reading alias.cnf
[06/09 10:52:19] Reading restrict.cnf
[06/09 10:52:19] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/09 10:52:19] 1.8.3
[06/09 10:52:19] MUSH restarted, PID 21676, at Tue Jun 09 10:52:19 2009
[06/09 10:52:19] ANALYZING: data/outdb
[06/09 10:52:19] ANALYZING: data/outdb (done)
[06/09 10:52:19] LOADING: data/outdb
[06/09 10:52:19] Loading database saved on Tue Jun 09 17:52:18 2009 UTC
[06/09 10:52:19] READING: done
[06/09 10:52:19] LOADING: data/outdb (done)
[06/09 10:52:19] LOADING: data/maildb
[06/09 10:52:19] LOADING: data/maildb (done)
[06/09 10:52:19] LOADING: data/chatdb
[06/09 10:52:19] LOADING: data/chatdb (done)
[06/09 10:52:19] Access file access.cnf not found.
[06/09 10:52:19] Reading /home/e/kilrathi/game/mush.cnf
[06/09 10:52:19] Reading alias.cnf
[06/09 10:52:19] Reading restrict.cnf
[06/09 10:52:19] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/09 10:52:19] PennPy: Initializing
_DB_KEY_NAME = 0
[06/09 10:52:19] Seeding OpenSSL random number pool.
[06/09 10:52:19] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/09 10:52:19] Spawning info slave, communicating using socketpair, pid 13622
[06/09 10:52:19] 1018 file descriptors available.
[06/09 10:52:19] RESTART FINISHED.
periodic() says: The current time is Tue Jun  9 10:52:20 2009
[06/09 10:52:20] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 10:59:11] Terminating info_slave pid 13622
[06/10 10:59:11] PennPy: Finalizing
[06/10 10:59:12] Setting ctype locale to en_US.UTF-8
[06/10 10:59:12] Setting time locale to en_US.UTF-8
[06/10 10:59:12] Setting messages locale to en_US.UTF-8
[06/10 10:59:12] Setting collate locale to en_US.UTF-8
[06/10 10:59:12] Seeded RNG from /dev/urandom
[06/10 10:59:12] Reading /home/e/kilrathi/game/mush.cnf
[06/10 10:59:12] Reading alias.cnf
[06/10 10:59:12] Reading restrict.cnf
[06/10 10:59:12] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 10:59:12] 1.8.3
[06/10 10:59:12] MUSH restarted, PID 21676, at Wed Jun 10 10:59:12 2009
[06/10 10:59:12] ANALYZING: data/outdb
[06/10 10:59:12] ANALYZING: data/outdb (done)
[06/10 10:59:12] LOADING: data/outdb
[06/10 10:59:12] Loading database saved on Wed Jun 10 17:59:11 2009 UTC
[06/10 10:59:12] READING: done
[06/10 10:59:12] LOADING: data/outdb (done)
[06/10 10:59:12] LOADING: data/maildb
[06/10 10:59:12] LOADING: data/maildb (done)
[06/10 10:59:12] LOADING: data/chatdb
[06/10 10:59:12] LOADING: data/chatdb (done)
[06/10 10:59:12] Access file access.cnf not found.
[06/10 10:59:12] Reading /home/e/kilrathi/game/mush.cnf
[06/10 10:59:12] Reading alias.cnf
[06/10 10:59:12] Reading restrict.cnf
[06/10 10:59:12] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 10:59:12] PennPy: Initializing
_DB_KEY_NAME = 0
Traceback (most recent call last):
  File "python/main.py", line 75, in <module>
    import honor
  File "python/honor.py", line 11
    return "Executor: " + str(executor) + " Caller: "  + str(caller) + "
                                                                       ^
SyntaxError: EOL while scanning single-quoted string
[06/10 10:59:12] PennPy: Failed to execute python/main.py
[06/10 10:59:12] Seeding OpenSSL random number pool.
[06/10 10:59:12] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 10:59:12] Spawning info slave, communicating using socketpair, pid 302
[06/10 10:59:12] 1018 file descriptors available.
[06/10 10:59:12] RESTART FINISHED.
[06/10 11:00:03] Terminating info_slave pid 302
[06/10 11:00:03] PennPy: Finalizing
[06/10 11:00:04] Setting ctype locale to en_US.UTF-8
[06/10 11:00:04] Setting time locale to en_US.UTF-8
[06/10 11:00:04] Setting messages locale to en_US.UTF-8
[06/10 11:00:04] Setting collate locale to en_US.UTF-8
[06/10 11:00:04] Seeded RNG from /dev/urandom
[06/10 11:00:04] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:00:04] Reading alias.cnf
[06/10 11:00:04] Reading restrict.cnf
[06/10 11:00:04] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 11:00:04] 1.8.3
[06/10 11:00:04] MUSH restarted, PID 21676, at Wed Jun 10 11:00:04 2009
[06/10 11:00:04] ANALYZING: data/outdb
[06/10 11:00:04] ANALYZING: data/outdb (done)
[06/10 11:00:04] LOADING: data/outdb
[06/10 11:00:04] Loading database saved on Wed Jun 10 18:00:03 2009 UTC
[06/10 11:00:04] READING: done
[06/10 11:00:04] LOADING: data/outdb (done)
[06/10 11:00:04] LOADING: data/maildb
[06/10 11:00:04] LOADING: data/maildb (done)
[06/10 11:00:04] LOADING: data/chatdb
[06/10 11:00:04] LOADING: data/chatdb (done)
[06/10 11:00:04] Access file access.cnf not found.
[06/10 11:00:04] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:00:04] Reading alias.cnf
[06/10 11:00:04] Reading restrict.cnf
[06/10 11:00:04] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 11:00:04] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 11:00:04] Seeding OpenSSL random number pool.
[06/10 11:00:04] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 11:00:04] Spawning info slave, communicating using socketpair, pid 346
[06/10 11:00:04] 1018 file descriptors available.
[06/10 11:00:04] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 11:00:05 2009
[06/10 11:00:05] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 11:04:25] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 77, in honor_pts
    return honor.get_points(victim)
  File "python/honor.py", line 10, in get_points
    victim = pennmush.api.locate("#" + str(enactor), victim, "PFX")
UnboundLocalError: local variable 'enactor' referenced before assignment
[06/10 11:27:21] Terminating info_slave pid 346
[06/10 11:27:21] PennPy: Finalizing
[06/10 11:27:21] Setting ctype locale to en_US.UTF-8
[06/10 11:27:21] Setting time locale to en_US.UTF-8
[06/10 11:27:21] Setting messages locale to en_US.UTF-8
[06/10 11:27:21] Setting collate locale to en_US.UTF-8
[06/10 11:27:21] Seeded RNG from /dev/urandom
[06/10 11:27:21] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:27:21] Reading alias.cnf
[06/10 11:27:21] Reading restrict.cnf
[06/10 11:27:21] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 11:27:21] 1.8.3
[06/10 11:27:21] MUSH restarted, PID 21676, at Wed Jun 10 11:27:21 2009
[06/10 11:27:21] ANALYZING: data/outdb
[06/10 11:27:21] ANALYZING: data/outdb (done)
[06/10 11:27:21] LOADING: data/outdb
[06/10 11:27:21] Loading database saved on Wed Jun 10 18:27:21 2009 UTC
[06/10 11:27:21] READING: done
[06/10 11:27:21] LOADING: data/outdb (done)
[06/10 11:27:21] LOADING: data/maildb
[06/10 11:27:21] LOADING: data/maildb (done)
[06/10 11:27:21] LOADING: data/chatdb
[06/10 11:27:21] LOADING: data/chatdb (done)
[06/10 11:27:21] Access file access.cnf not found.
[06/10 11:27:21] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:27:21] Reading alias.cnf
[06/10 11:27:21] Reading restrict.cnf
[06/10 11:27:21] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 11:27:21] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 11:27:21] Seeding OpenSSL random number pool.
[06/10 11:27:21] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 11:27:21] Spawning info slave, communicating using socketpair, pid 928
[06/10 11:27:21] 1018 file descriptors available.
[06/10 11:27:21] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 11:27:22 2009
[06/10 11:27:22] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 11:27:24] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 80, in colortable
    pennmush.notify(enactor, t.string()) 
TypeError: 'int' object is not iterable
[06/10 11:27:54] Terminating info_slave pid 928
[06/10 11:27:54] PennPy: Finalizing
[06/10 11:27:54] Setting ctype locale to en_US.UTF-8
[06/10 11:27:54] Setting time locale to en_US.UTF-8
[06/10 11:27:54] Setting messages locale to en_US.UTF-8
[06/10 11:27:54] Setting collate locale to en_US.UTF-8
[06/10 11:27:54] Seeded RNG from /dev/urandom
[06/10 11:27:54] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:27:54] Reading alias.cnf
[06/10 11:27:54] Reading restrict.cnf
[06/10 11:27:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 11:27:54] 1.8.3
[06/10 11:27:54] MUSH restarted, PID 21676, at Wed Jun 10 11:27:54 2009
[06/10 11:27:54] ANALYZING: data/outdb
[06/10 11:27:54] ANALYZING: data/outdb (done)
[06/10 11:27:54] LOADING: data/outdb
[06/10 11:27:54] Loading database saved on Wed Jun 10 18:27:54 2009 UTC
[06/10 11:27:54] READING: done
[06/10 11:27:54] LOADING: data/outdb (done)
[06/10 11:27:54] LOADING: data/maildb
[06/10 11:27:54] LOADING: data/maildb (done)
[06/10 11:27:54] LOADING: data/chatdb
[06/10 11:27:54] LOADING: data/chatdb (done)
[06/10 11:27:54] Access file access.cnf not found.
[06/10 11:27:54] Reading /home/e/kilrathi/game/mush.cnf
[06/10 11:27:54] Reading alias.cnf
[06/10 11:27:54] Reading restrict.cnf
[06/10 11:27:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 11:27:54] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 11:27:54] Seeding OpenSSL random number pool.
[06/10 11:27:54] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 11:27:54] Spawning info slave, communicating using socketpair, pid 941
[06/10 11:27:54] 1018 file descriptors available.
[06/10 11:27:54] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 11:27:55 2009
[06/10 11:27:55] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 13:44:42] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 70, in reload
    __builtins__.reload(sys.modules[module])
KeyError: 'main'
[06/10 13:45:39] Terminating info_slave pid 941
[06/10 13:45:39] PennPy: Finalizing
[06/10 13:45:40] Setting ctype locale to en_US.UTF-8
[06/10 13:45:40] Setting time locale to en_US.UTF-8
[06/10 13:45:40] Setting messages locale to en_US.UTF-8
[06/10 13:45:40] Setting collate locale to en_US.UTF-8
[06/10 13:45:40] Seeded RNG from /dev/urandom
[06/10 13:45:40] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:45:40] Reading alias.cnf
[06/10 13:45:40] Reading restrict.cnf
[06/10 13:45:40] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 13:45:40] 1.8.3
[06/10 13:45:40] MUSH restarted, PID 21676, at Wed Jun 10 13:45:40 2009
[06/10 13:45:40] ANALYZING: data/outdb
[06/10 13:45:40] ANALYZING: data/outdb (done)
[06/10 13:45:40] LOADING: data/outdb
[06/10 13:45:40] Loading database saved on Wed Jun 10 20:45:39 2009 UTC
[06/10 13:45:40] READING: done
[06/10 13:45:40] LOADING: data/outdb (done)
[06/10 13:45:40] LOADING: data/maildb
[06/10 13:45:40] LOADING: data/maildb (done)
[06/10 13:45:40] LOADING: data/chatdb
[06/10 13:45:40] LOADING: data/chatdb (done)
[06/10 13:45:40] Access file access.cnf not found.
[06/10 13:45:40] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:45:40] Reading alias.cnf
[06/10 13:45:40] Reading restrict.cnf
[06/10 13:45:40] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 13:45:40] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 13:45:40] Seeding OpenSSL random number pool.
[06/10 13:45:40] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 13:45:40] Spawning info slave, communicating using socketpair, pid 2730
[06/10 13:45:40] 1018 file descriptors available.
[06/10 13:45:40] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 13:45:41 2009
[06/10 13:45:41] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 13:46:28] Terminating info_slave pid 2730
[06/10 13:46:28] PennPy: Finalizing
[06/10 13:46:29] Setting ctype locale to en_US.UTF-8
[06/10 13:46:29] Setting time locale to en_US.UTF-8
[06/10 13:46:29] Setting messages locale to en_US.UTF-8
[06/10 13:46:29] Setting collate locale to en_US.UTF-8
[06/10 13:46:29] Seeded RNG from /dev/urandom
[06/10 13:46:29] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:46:29] Reading alias.cnf
[06/10 13:46:29] Reading restrict.cnf
[06/10 13:46:29] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 13:46:29] 1.8.3
[06/10 13:46:29] MUSH restarted, PID 21676, at Wed Jun 10 13:46:29 2009
[06/10 13:46:29] ANALYZING: data/outdb
[06/10 13:46:29] ANALYZING: data/outdb (done)
[06/10 13:46:29] LOADING: data/outdb
[06/10 13:46:29] Loading database saved on Wed Jun 10 20:46:28 2009 UTC
[06/10 13:46:29] READING: done
[06/10 13:46:29] LOADING: data/outdb (done)
[06/10 13:46:29] LOADING: data/maildb
[06/10 13:46:29] LOADING: data/maildb (done)
[06/10 13:46:29] LOADING: data/chatdb
[06/10 13:46:29] LOADING: data/chatdb (done)
[06/10 13:46:29] Access file access.cnf not found.
[06/10 13:46:29] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:46:29] Reading alias.cnf
[06/10 13:46:29] Reading restrict.cnf
[06/10 13:46:29] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 13:46:29] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 13:46:29] Seeding OpenSSL random number pool.
[06/10 13:46:29] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 13:46:29] Spawning info slave, communicating using socketpair, pid 2732
[06/10 13:46:29] 1018 file descriptors available.
[06/10 13:46:29] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 13:46:30 2009
[06/10 13:46:30] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 13:53:53] Terminating info_slave pid 2732
[06/10 13:53:53] PennPy: Finalizing
[06/10 13:53:54] Setting ctype locale to en_US.UTF-8
[06/10 13:53:54] Setting time locale to en_US.UTF-8
[06/10 13:53:54] Setting messages locale to en_US.UTF-8
[06/10 13:53:54] Setting collate locale to en_US.UTF-8
[06/10 13:53:54] Seeded RNG from /dev/urandom
[06/10 13:53:54] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:53:54] Reading alias.cnf
[06/10 13:53:54] Reading restrict.cnf
[06/10 13:53:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 13:53:54] 1.8.3
[06/10 13:53:54] MUSH restarted, PID 21676, at Wed Jun 10 13:53:54 2009
[06/10 13:53:54] ANALYZING: data/outdb
[06/10 13:53:54] ANALYZING: data/outdb (done)
[06/10 13:53:54] LOADING: data/outdb
[06/10 13:53:54] Loading database saved on Wed Jun 10 20:53:53 2009 UTC
[06/10 13:53:54] READING: done
[06/10 13:53:54] LOADING: data/outdb (done)
[06/10 13:53:54] LOADING: data/maildb
[06/10 13:53:54] LOADING: data/maildb (done)
[06/10 13:53:54] LOADING: data/chatdb
[06/10 13:53:54] LOADING: data/chatdb (done)
[06/10 13:53:54] Access file access.cnf not found.
[06/10 13:53:54] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:53:54] Reading alias.cnf
[06/10 13:53:54] Reading restrict.cnf
[06/10 13:53:54] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 13:53:54] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 13:53:54] Seeding OpenSSL random number pool.
[06/10 13:53:54] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 13:53:54] Spawning info slave, communicating using socketpair, pid 2787
[06/10 13:53:54] 1018 file descriptors available.
[06/10 13:53:54] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 13:53:55 2009
[06/10 13:53:55] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 13:55:11] Terminating info_slave pid 2787
[06/10 13:55:11] PennPy: Finalizing
[06/10 13:55:11] Setting ctype locale to en_US.UTF-8
[06/10 13:55:11] Setting time locale to en_US.UTF-8
[06/10 13:55:11] Setting messages locale to en_US.UTF-8
[06/10 13:55:11] Setting collate locale to en_US.UTF-8
[06/10 13:55:11] Seeded RNG from /dev/urandom
[06/10 13:55:11] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:55:11] Reading alias.cnf
[06/10 13:55:11] Reading restrict.cnf
[06/10 13:55:11] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 13:55:11] 1.8.3
[06/10 13:55:11] MUSH restarted, PID 21676, at Wed Jun 10 13:55:11 2009
[06/10 13:55:11] ANALYZING: data/outdb
[06/10 13:55:11] ANALYZING: data/outdb (done)
[06/10 13:55:11] LOADING: data/outdb
[06/10 13:55:11] Loading database saved on Wed Jun 10 20:55:11 2009 UTC
[06/10 13:55:11] READING: done
[06/10 13:55:11] LOADING: data/outdb (done)
[06/10 13:55:11] LOADING: data/maildb
[06/10 13:55:11] LOADING: data/maildb (done)
[06/10 13:55:11] LOADING: data/chatdb
[06/10 13:55:11] LOADING: data/chatdb (done)
[06/10 13:55:11] Access file access.cnf not found.
[06/10 13:55:11] Reading /home/e/kilrathi/game/mush.cnf
[06/10 13:55:11] Reading alias.cnf
[06/10 13:55:11] Reading restrict.cnf
[06/10 13:55:11] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 13:55:11] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 13:55:11] Seeding OpenSSL random number pool.
[06/10 13:55:11] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 13:55:11] Spawning info slave, communicating using socketpair, pid 2847
[06/10 13:55:11] 1018 file descriptors available.
[06/10 13:55:11] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 13:55:12 2009
[06/10 13:55:12] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 14:07:27] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 70, in reload
    __builtins__.reload(sys.modules[module])
KeyError: 'util'
[06/10 14:07:44] Terminating info_slave pid 2847
[06/10 14:07:44] PennPy: Finalizing
[06/10 14:07:45] Setting ctype locale to en_US.UTF-8
[06/10 14:07:45] Setting time locale to en_US.UTF-8
[06/10 14:07:45] Setting messages locale to en_US.UTF-8
[06/10 14:07:45] Setting collate locale to en_US.UTF-8
[06/10 14:07:45] Seeded RNG from /dev/urandom
[06/10 14:07:45] Reading /home/e/kilrathi/game/mush.cnf
[06/10 14:07:45] Reading alias.cnf
[06/10 14:07:45] Reading restrict.cnf
[06/10 14:07:45] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 14:07:45] 1.8.3
[06/10 14:07:45] MUSH restarted, PID 21676, at Wed Jun 10 14:07:45 2009
[06/10 14:07:45] ANALYZING: data/outdb
[06/10 14:07:45] ANALYZING: data/outdb (done)
[06/10 14:07:45] LOADING: data/outdb
[06/10 14:07:45] Loading database saved on Wed Jun 10 21:07:44 2009 UTC
[06/10 14:07:45] READING: done
[06/10 14:07:45] LOADING: data/outdb (done)
[06/10 14:07:45] LOADING: data/maildb
[06/10 14:07:45] LOADING: data/maildb (done)
[06/10 14:07:45] LOADING: data/chatdb
[06/10 14:07:45] LOADING: data/chatdb (done)
[06/10 14:07:45] Access file access.cnf not found.
[06/10 14:07:45] Reading /home/e/kilrathi/game/mush.cnf
[06/10 14:07:45] Reading alias.cnf
[06/10 14:07:45] Reading restrict.cnf
[06/10 14:07:45] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 14:07:45] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 14:07:45] Seeding OpenSSL random number pool.
[06/10 14:07:45] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 14:07:45] Spawning info slave, communicating using socketpair, pid 2971
[06/10 14:07:45] 1018 file descriptors available.
[06/10 14:07:45] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 14:07:46 2009
[06/10 14:07:46] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 14:09:51] Terminating info_slave pid 2971
[06/10 14:09:51] PennPy: Finalizing
[06/10 14:09:52] Setting ctype locale to en_US.UTF-8
[06/10 14:09:52] Setting time locale to en_US.UTF-8
[06/10 14:09:52] Setting messages locale to en_US.UTF-8
[06/10 14:09:52] Setting collate locale to en_US.UTF-8
[06/10 14:09:52] Seeded RNG from /dev/urandom
[06/10 14:09:52] Reading /home/e/kilrathi/game/mush.cnf
[06/10 14:09:52] Reading alias.cnf
[06/10 14:09:52] Reading restrict.cnf
[06/10 14:09:52] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/10 14:09:52] 1.8.3
[06/10 14:09:52] MUSH restarted, PID 21676, at Wed Jun 10 14:09:52 2009
[06/10 14:09:52] ANALYZING: data/outdb
[06/10 14:09:52] ANALYZING: data/outdb (done)
[06/10 14:09:52] LOADING: data/outdb
[06/10 14:09:52] Loading database saved on Wed Jun 10 21:09:51 2009 UTC
[06/10 14:09:52] READING: done
[06/10 14:09:52] LOADING: data/outdb (done)
[06/10 14:09:52] LOADING: data/maildb
[06/10 14:09:52] LOADING: data/maildb (done)
[06/10 14:09:52] LOADING: data/chatdb
[06/10 14:09:52] LOADING: data/chatdb (done)
[06/10 14:09:52] Access file access.cnf not found.
[06/10 14:09:52] Reading /home/e/kilrathi/game/mush.cnf
[06/10 14:09:52] Reading alias.cnf
[06/10 14:09:52] Reading restrict.cnf
[06/10 14:09:52] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/10 14:09:52] PennPy: Initializing
_DB_KEY_NAME = 0
[06/10 14:09:52] Seeding OpenSSL random number pool.
[06/10 14:09:52] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/10 14:09:52] Spawning info slave, communicating using socketpair, pid 3051
[06/10 14:09:52] 1018 file descriptors available.
[06/10 14:09:52] RESTART FINISHED.
periodic() says: The current time is Wed Jun 10 14:09:53 2009
[06/10 14:09:53] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/10 14:09:57] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 97, in honor_log_view
    honor.log_view(victim)
  File "python/honor.py", line 24, in log_view
    pennmush.notify([victim], util.titlebar("Honor logs"))
TypeError: argument 2 must be string, not Text
[06/10 14:15:38] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 70, in reload
    __builtins__.reload(sys.modules[module])
  File "python/util.py", line 10
    return ansistyle.Text(010,">--","-" * (70-len(text)),,0110,"[",0170,text,0110,"]",010,"---<").string()
                                                         ^
SyntaxError: invalid syntax
[06/10 14:31:43] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 94, in honor_pts
    return honor.pts(victim)
  File "python/honor.py", line 15, in pts
    victim = int(victim.lstrip("#"))
ValueError: invalid literal for int() with base 10: 'zran'
[06/10 14:43:01] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 94, in honor_pts
    return honor.pts(victim)
  File "python/honor.py", line 15, in pts
    victim = int(victim.lstrip("#"))
ValueError: invalid literal for int() with base 10: 'zran'
[06/10 14:43:13] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 97, in honor_log_view
    honor.log_view(victim)
  File "python/honor.py", line 34, in log_view
    pennmush.notify([enactor], " " + dt.strftime("%d/%m/%Y %H:%m") +str(delta) + " " + str(balance))
AttributeError: 'NoneType' object has no attribute 'strftime'
[06/10 14:45:45] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 70, in reload
    __builtins__.reload(sys.modules[module])
  File "python/honor.py", line 36
    pennmush.notify([enactor], util.footerbar())
           ^
SyntaxError: invalid syntax
[06/10 14:46:10] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 97, in honor_log_view
    honor.log_view(victim)
  File "python/honor.py", line 35, in log_view
    pennmush.notify([enactor], " " + dt.strftime("%d/%m/%y %H:%m") + "  " + string.rjust(delta,6) + "  " + string.rjust(balance,6))
  File "/usr/lib/python2.5/string.py", line 440, in rjust
    return s.rjust(width, *args)
AttributeError: 'long' object has no attribute 'rjust'
[06/10 14:52:06] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 97, in honor_log_view
    honor.log_view(victim)
  File "python/honor.py", line 35, in log_view
    pennmush.notify([enactor], util.footerbar())
TypeError: argument 2 must be string, not Text
[06/15 13:40:05] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 97, in honor_log_view
    honor.log_view(victim)
  File "python/honor.py", line 30, in log_view
    cursor.execute("SELECT delta, balance, description, dt FROM honor_log WHERE victim = " + str(victim) + " ORDER BY dt desc LIMIT 20")
  File "/usr/lib/pymodules/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
[06/15 13:42:35] Terminating info_slave pid 3051
[06/15 13:42:35] PennPy: Finalizing
[06/15 13:42:36] Setting ctype locale to en_US.UTF-8
[06/15 13:42:36] Setting time locale to en_US.UTF-8
[06/15 13:42:36] Setting messages locale to en_US.UTF-8
[06/15 13:42:36] Setting collate locale to en_US.UTF-8
[06/15 13:42:36] Seeded RNG from /dev/urandom
[06/15 13:42:36] Reading /home/e/kilrathi/game/mush.cnf
[06/15 13:42:36] Reading alias.cnf
[06/15 13:42:36] Reading restrict.cnf
[06/15 13:42:36] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/15 13:42:36] 1.8.3
[06/15 13:42:36] MUSH restarted, PID 21676, at Mon Jun 15 13:42:36 2009
[06/15 13:42:36] ANALYZING: data/outdb
[06/15 13:42:36] ANALYZING: data/outdb (done)
[06/15 13:42:36] LOADING: data/outdb
[06/15 13:42:36] Loading database saved on Mon Jun 15 20:42:35 2009 UTC
[06/15 13:42:36] READING: done
[06/15 13:42:36] LOADING: data/outdb (done)
[06/15 13:42:36] LOADING: data/maildb
[06/15 13:42:36] LOADING: data/maildb (done)
[06/15 13:42:36] LOADING: data/chatdb
[06/15 13:42:36] LOADING: data/chatdb (done)
[06/15 13:42:36] Access file access.cnf not found.
[06/15 13:42:36] Reading /home/e/kilrathi/game/mush.cnf
[06/15 13:42:36] Reading alias.cnf
[06/15 13:42:36] Reading restrict.cnf
[06/15 13:42:36] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/15 13:42:36] PennPy: Initializing
_DB_KEY_NAME = 0
[06/15 13:42:36] Seeding OpenSSL random number pool.
[06/15 13:42:36] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
[06/15 13:42:36] Spawning info slave, communicating using socketpair, pid 12573
[06/15 13:42:36] 1018 file descriptors available.
[06/15 13:42:36] RESTART FINISHED.
info_slave: trying poll event loop... ok. Using poll.
periodic() says: The current time is Mon Jun 15 13:42:37 2009
[06/15 13:42:37] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/16 15:41:13] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 94, in honor_pts
    return honor.pts(victim)
  File "python/honor.py", line 17, in pts
    cursor.execute("SELECT balance FROM honor_log WHERE victim = " + str(victim) + " ORDER BY dt desc LIMIT 1")
  File "/usr/lib/pymodules/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
[06/16 15:41:15] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 94, in honor_pts
    return honor.pts(victim)
  File "python/honor.py", line 15, in pts
    victim = int(victim.lstrip("#"))
ValueError: invalid literal for int() with base 10: 'zran'
[06/16 15:41:16] Terminating info_slave pid 12573
[06/16 15:41:16] PennPy: Finalizing
[06/16 15:41:17] Setting ctype locale to en_US.UTF-8
[06/16 15:41:17] Setting time locale to en_US.UTF-8
[06/16 15:41:17] Setting messages locale to en_US.UTF-8
[06/16 15:41:17] Setting collate locale to en_US.UTF-8
[06/16 15:41:17] Seeded RNG from /dev/urandom
[06/16 15:41:17] Reading /home/e/kilrathi/game/mush.cnf
[06/16 15:41:17] Reading alias.cnf
[06/16 15:41:17] Reading restrict.cnf
[06/16 15:41:17] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/16 15:41:17] 1.8.3
[06/16 15:41:17] MUSH restarted, PID 21676, at Tue Jun 16 15:41:17 2009
[06/16 15:41:17] ANALYZING: data/outdb
[06/16 15:41:17] ANALYZING: data/outdb (done)
[06/16 15:41:17] LOADING: data/outdb
[06/16 15:41:17] Loading database saved on Tue Jun 16 22:41:16 2009 UTC
[06/16 15:41:17] READING: done
[06/16 15:41:17] LOADING: data/outdb (done)
[06/16 15:41:17] LOADING: data/maildb
[06/16 15:41:17] LOADING: data/maildb (done)
[06/16 15:41:17] LOADING: data/chatdb
[06/16 15:41:17] LOADING: data/chatdb (done)
[06/16 15:41:17] Access file access.cnf not found.
[06/16 15:41:17] Reading /home/e/kilrathi/game/mush.cnf
[06/16 15:41:17] Reading alias.cnf
[06/16 15:41:17] Reading restrict.cnf
[06/16 15:41:17] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/16 15:41:17] PennPy: Initializing
_DB_KEY_NAME = 0
[06/16 15:41:17] Seeding OpenSSL random number pool.
[06/16 15:41:17] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/16 15:41:17] Spawning info slave, communicating using socketpair, pid 11297
[06/16 15:41:17] 1018 file descriptors available.
[06/16 15:41:17] RESTART FINISHED.
periodic() says: The current time is Tue Jun 16 15:41:18 2009
[06/16 15:41:18] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/16 15:41:19] PennPy: Python exception:
Traceback (most recent call last):
  File "python/main.py", line 94, in honor_pts
    return honor.pts(victim)
  File "python/honor.py", line 15, in pts
    victim = int(victim.lstrip("#"))
ValueError: invalid literal for int() with base 10: 'zran'
[06/16 15:44:23] Terminating info_slave pid 11297
[06/16 15:44:23] PennPy: Finalizing
[06/16 15:44:24] Setting ctype locale to en_US.UTF-8
[06/16 15:44:24] Setting time locale to en_US.UTF-8
[06/16 15:44:24] Setting messages locale to en_US.UTF-8
[06/16 15:44:24] Setting collate locale to en_US.UTF-8
[06/16 15:44:24] Seeded RNG from /dev/urandom
[06/16 15:44:24] Reading /home/e/kilrathi/game/mush.cnf
[06/16 15:44:24] Reading alias.cnf
[06/16 15:44:24] Reading restrict.cnf
[06/16 15:44:24] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
Redirecting stderr to log/netmush.log
[06/16 15:44:24] 1.8.3
[06/16 15:44:24] MUSH restarted, PID 21676, at Tue Jun 16 15:44:24 2009
[06/16 15:44:24] ANALYZING: data/outdb
[06/16 15:44:24] ANALYZING: data/outdb (done)
[06/16 15:44:24] LOADING: data/outdb
[06/16 15:44:24] Loading database saved on Tue Jun 16 22:44:23 2009 UTC
[06/16 15:44:24] READING: done
[06/16 15:44:24] LOADING: data/outdb (done)
[06/16 15:44:24] LOADING: data/maildb
[06/16 15:44:24] LOADING: data/maildb (done)
[06/16 15:44:24] LOADING: data/chatdb
[06/16 15:44:24] LOADING: data/chatdb (done)
[06/16 15:44:24] Access file access.cnf not found.
[06/16 15:44:24] Reading /home/e/kilrathi/game/mush.cnf
[06/16 15:44:24] Reading alias.cnf
[06/16 15:44:24] Reading restrict.cnf
[06/16 15:44:24] CONFIG: directive 'exit_flags' missing from cnf file, using default value.
[06/16 15:44:24] PennPy: Initializing
_DB_KEY_NAME = 0
[06/16 15:44:24] Seeding OpenSSL random number pool.
[06/16 15:44:24] Seeded after 1 cycle.
Unable to load server certificate - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:720:
Unable to load private key - only anonymous ciphers supported.
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:352:fopen('server-key.crt','r')
21676:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:354:
21676:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
Unable to load CA certificates
21676:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/usr/share/ssl/certs/ca-bundle.crt','r')
21676:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:
21676:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:274:
info_slave: trying poll event loop... ok. Using poll.
[06/16 15:44:24] Spawning info slave, communicating using socketpair, pid 11345
[06/16 15:44:24] 1018 file descriptors available.
[06/16 15:44:24] RESTART FINISHED.
periodic() says: The current time is Tue Jun 16 15:44:25 2009
[06/16 15:44:25] PennPy: Timer hook threw exception
Traceback (most recent call last):
  File "python/main.py", line 57, in periodic
    raise AssertionError("I've been bad")
AssertionError: I've been bad
[06/17 11:20:01] Couldn't open cached text file 'txt/quit.txt'
